### ISSUE TITLE
Bot answers with recursion

### ISSUE THREAD

**Issue by daggett206** [vitalyavolyn/node-vk-bot#15]
Hi, I just tried this simple code and got an answer with recursion

    bot.get(/hi|hello|hey/i, message => {
     
        bot.send('whats up man!', message.peer_id)
    })

    bot.on('command-notfound', msg => {
        console.log(msg);
        bot.send('What?', msg.peer_id)
    })
![image](https://user-images.githubusercontent.com/14615740/31888075-aba240a6-b80b-11e7-8cdb-11ed64a24b1f.png)

it seems like 'whats up man!' is identified as 'command-notfound' and starts to send 'What?' and so on.
I think the bot shouldn't respond to its messages at all

**Comment by vitalyavolyn** [comment]
I can't reproduce error with your code... Are you using the latest version (0.2.2)?

**Comment by daggett206** [comment]
I noticed it happens if you initialize Bot with both **prefix** and **prefixOnlyInChats**.
When I initialize only with **prefix** or **prefixOnlyInChats** it works great!

**Comment by vitalyavolyn** [comment]
I've fixed this issue and published a new version
