### ISSUE TITLE
Do nothing if send attachment without text

### ISSUE THREAD

**Issue by daggett206** [vitalyavolyn/node-vk-bot#16]
I think needs to add one more checking (for attachments in the message) in `_update` method.

`
const hasAttachments : boolean = !!Object.keys(update[7]).length;
`

and then add this to existing checking

`
if (!text && !hasAttachments) return
`

so now it won't break if I just forward any attachment without text to bot.

what do you think?

**Comment by vitalyavolyn** [comment]
I think that this is a great idea! Feel free to open a PR, I'll merge it

**Comment by daggett206** [comment]
[Done](https://github.com/vitalyavolyn/node-vk-bot/pull/17)
