### ISSUE TITLE
Ненужное приведение к  json

### ISSUE THREAD

**Issue by uza-anna** [vitalyavolyn/node-vk-bot#70]
https://github.com/vitalyavolyn/node-vk-bot/blob/922654cc5c10cc9bd1c6a980387f9905f72ec32a/src/index.ts#L117
вот тут.

```
 if (JSON.stringify(JSON.parse(msg.payload)) === (jsonString)){
```
корректный вариант. Иначе падает, так как вк изменил формат данных

**Comment by vikegart** [comment]
Такая же проблема. При получении сообщения с payload - падает в этом месте, при попытке распарсить JSON, так как в jsonString прилетает распаршенный объект.

**Comment by vitalyavolyn** [comment]
Спасибо! Сейчас приму реквест
